/** Shared localized releases data — imported by seed-releases.ts and postgres.ts */

export interface LocalizedRelease {
  version: string;
  released_at: string;
  highlight: { en: string; es: string; fr: string; de: string };
  features: { en: string[]; es: string[]; fr: string[]; de: string[] };
  fixes: { en: string[]; es: string[]; fr: string[]; de: string[] };
}

export const RELEASES: LocalizedRelease[] = [
  {
    version: "v1.3.0",
    released_at: "2026-03-13",
    highlight: {
      en: "Database-backed changelog with full EN/ES/FR/DE locale support, new-release notification dot, and sticky Manage Agent header.",
      es: "Changelog respaldado por base de datos con soporte completo de idiomas EN/ES/FR/DE, punto de notificación de nueva versión y encabezado sticky de Gestión de Agente.",
      fr: "Journal des modifications basé sur la base de données avec support complet des langues EN/ES/FR/DE, point de notification de nouvelle version et en-tête sticky de Gestion d'Agent.",
      de: "Datenbank-gestütztes Changelog mit vollständiger EN/ES/FR/DE-Sprachunterstützung, Benachrichtigungspunkt für neue Versionen und fixierter Manage-Agent-Header.",
    },
    features: {
      en: [
        "🗄️ DB-backed changelog — release notes stored in PostgreSQL/SQLite with ON CONFLICT upsert; auto-seeded on every backend deploy",
        "🌐 Full locale support — highlight, features, and fixes translated into EN, ES, FR, and DE; switches instantly with the language selector",
        "🔵 New-release notification dot — blue dot on the changelog button for unseen versions; dismissed on first open, persisted in localStorage",
        "📌 Sticky Manage Agent header — AgentIdentityHeader, EquityCurveChart, and MetricsRow stay visible while scrolling",
        "🔧 AutopilotControlCard — ExecutionLog only renders when Telegram is configured",
      ],
      es: [
        "🗄️ Changelog respaldado por BD — notas de versión almacenadas en PostgreSQL/SQLite con upsert ON CONFLICT; sembradas automáticamente en cada despliegue",
        "🌐 Soporte completo de idiomas — highlight, características y correcciones traducidos a EN, ES, FR y DE; cambia instantáneamente con el selector de idioma",
        "🔵 Punto de notificación de nueva versión — punto azul en el botón changelog para versiones no vistas; descartado al primer clic, persistido en localStorage",
        "📌 Encabezado sticky de Gestión de Agente — AgentIdentityHeader, EquityCurveChart y MetricsRow permanecen visibles al desplazarse",
        "🔧 AutopilotControlCard — ExecutionLog solo se renderiza cuando Telegram está configurado",
      ],
      fr: [
        "🗄️ Changelog basé sur la BD — notes de version stockées dans PostgreSQL/SQLite avec upsert ON CONFLICT ; semées automatiquement à chaque déploiement",
        "🌐 Support complet des langues — highlight, fonctionnalités et correctifs traduits en EN, ES, FR et DE ; change instantanément avec le sélecteur de langue",
        "🔵 Point de notification de nouvelle version — point bleu sur le bouton changelog pour les versions non vues ; rejeté à la première ouverture, persisté dans localStorage",
        "📌 En-tête sticky de Gestion d'Agent — AgentIdentityHeader, EquityCurveChart et MetricsRow restent visibles en faisant défiler",
        "🔧 AutopilotControlCard — ExecutionLog ne s'affiche que lorsque Telegram est configuré",
      ],
      de: [
        "🗄️ DB-gestütztes Changelog — Versionshinweise in PostgreSQL/SQLite mit ON CONFLICT Upsert; bei jedem Deploy automatisch geseedet",
        "🌐 Vollständige Sprachunterstützung — Highlight, Features und Fixes in EN, ES, FR und DE; wechselt sofort mit dem Sprachselektor",
        "🔵 Benachrichtigungspunkt für neue Versionen — blauer Punkt auf dem Changelog-Button für ungesehene Versionen; beim ersten Öffnen verworfen, in localStorage gespeichert",
        "📌 Fixierter Manage-Agent-Header — bleibt beim Scrollen durch Positionen und Logs sichtbar",
        "🔧 AutopilotControlCard — ExecutionLog wird nur angezeigt wenn Telegram konfiguriert ist",
      ],
    },
    fixes: {
      en: [
        "🔧 layout.tsx: overflowX hidden → clip to fix sticky child element rendering",
        "⚙️ ExecutionLog: trade id coercion ?? → || for safer fallback",
        "🗑️ Old static RELEASES array removed from frontend bundle — data now served from API",
      ],
      es: [
        "🔧 layout.tsx: overflowX hidden → clip para corregir el renderizado de elementos sticky",
        "⚙️ ExecutionLog: coerción de id de trade ?? → || para fallback más seguro",
        "🗑️ Array RELEASES estático eliminado del bundle del frontend — los datos ahora vienen de la API",
      ],
      fr: [
        "🔧 layout.tsx : overflowX hidden → clip pour corriger le rendu des éléments sticky",
        "⚙️ ExecutionLog : coercition d'id de trade ?? → || pour un fallback plus sûr",
        "🗑️ Ancien tableau RELEASES statique supprimé du bundle frontend — les données viennent de l'API",
      ],
      de: [
        "🔧 layout.tsx: overflowX hidden → clip zur Behebung von Sticky-Element-Rendering",
        "⚙️ ExecutionLog: Trade-ID-Koerzion ?? → || für sichereren Fallback",
        "🗑️ Altes statisches RELEASES-Array aus dem Frontend-Bundle entfernt — Daten kommen jetzt von der API",
      ],
    },
  },
  {
    version: "v1.2.0",
    released_at: "2026-03-13",
    highlight: {
      en: "ScannerFeed redesign, PolymarketStatus deep metrics, relay pipeline streaming, market scanner upgrades, and live dashboard data binding.",
      es: "Rediseño de ScannerFeed, métricas profundas de PolymarketStatus, streaming del pipeline de retransmisión, mejoras del escáner de mercado y vinculación de datos en vivo del dashboard.",
      fr: "Refonte de ScannerFeed, métriques approfondies de PolymarketStatus, streaming du pipeline de relais, améliorations du scanner de marché et liaison de données en direct du tableau de bord.",
      de: "ScannerFeed-Neugestaltung, tiefe PolymarketStatus-Metriken, Relay-Pipeline-Streaming, Market-Scanner-Verbesserungen und Live-Dashboard-Datenbindung.",
    },
    features: {
      en: [
        "📡 ScannerFeed overhaul — full UI redesign with live market scanning, category filters, confidence scoring, probability bars, and real-time Socket.io updates",
        "📊 PolymarketStatusCard — expanded with wallet balance, active positions, P&L tracking, volume metrics, and richer connection states",
        "💬 RelayChatSidebar — improved message rendering, typing indicators, and agent pipeline display",
        "🏠 DashboardPageClient — live stats queries and real-time data bindings via React Query",
        "🔌 Providers — ReactQuery and SocketContext wired at app root for global real-time state",
        "🔁 agentChat relay pipeline — full AURA→FLUX→CLAUSE→ORACLE→EDGE→LUCIFER→SIGMA streaming with SSE and per-message token tracking",
        "🔍 Market scanner — real-time scanning with category tagging, confidence scoring, and Polymarket API integration",
        "⚖️ Risk routes — refined position sizing logic and L3 risk assessment endpoints",
        "🧩 Linked agent utilities — pipeline wiring and resolution helpers updated",
      ],
      es: [
        "📡 Renovación de ScannerFeed — rediseño completo de UI con escaneo de mercado en vivo, filtros de categoría, puntuación de confianza, barras de probabilidad y actualizaciones en tiempo real via Socket.io",
        "📊 PolymarketStatusCard — ampliado con saldo de billetera, posiciones activas, seguimiento de P&L, métricas de volumen y estados de conexión más detallados",
        "💬 RelayChatSidebar — renderizado de mensajes mejorado, indicadores de escritura y visualización del pipeline de agentes",
        "🏠 DashboardPageClient — consultas de estadísticas en vivo y vinculación de datos en tiempo real vía React Query",
        "🔌 Providers — ReactQuery y SocketContext configurados en la raíz de la app para estado global en tiempo real",
        "🔁 Pipeline de retransmisión agentChat — streaming completo AURA→FLUX→CLAUSE→ORACLE→EDGE→LUCIFER→SIGMA con SSE y rastreo de tokens por mensaje",
        "🔍 Escáner de mercado — escaneo en tiempo real con etiquetado de categorías, puntuación de confianza e integración con la API de Polymarket",
        "⚖️ Rutas de riesgo — lógica de dimensionamiento de posición refinada y endpoints de evaluación de riesgo L3",
        "🧩 Utilidades de agente vinculado — helpers de cableado y resolución del pipeline actualizados",
      ],
      fr: [
        "📡 Refonte de ScannerFeed — redesign complet de l'UI avec scan de marché en direct, filtres de catégorie, score de confiance, barres de probabilité et mises à jour en temps réel via Socket.io",
        "📊 PolymarketStatusCard — enrichi avec solde du portefeuille, positions actives, suivi P&L, métriques de volume et états de connexion plus riches",
        "💬 RelayChatSidebar — rendu des messages amélioré, indicateurs de frappe et affichage du pipeline d'agents",
        "🏠 DashboardPageClient — requêtes de statistiques en direct et liaisons de données en temps réel via React Query",
        "🔌 Providers — ReactQuery et SocketContext câblés à la racine de l'app pour un état global en temps réel",
        "🔁 Pipeline de relais agentChat — streaming complet AURA→FLUX→CLAUSE→ORACLE→EDGE→LUCIFER→SIGMA avec SSE et suivi des tokens par message",
        "🔍 Scanner de marché — scan en temps réel avec tags de catégorie, score de confiance et intégration API Polymarket",
        "⚖️ Routes de risque — logique de dimensionnement des positions affinée et endpoints d'évaluation de risque L3",
        "🧩 Utilitaires d'agents liés — helpers de câblage et de résolution du pipeline mis à jour",
      ],
      de: [
        "📡 ScannerFeed-Überarbeitung — vollständiges UI-Redesign mit Live-Markt-Scanning, Kategorie-Filtern, Vertrauens-Scoring, Wahrscheinlichkeitsbalken und Echtzeit-Socket.io-Updates",
        "📊 PolymarketStatusCard — erweitert um Wallet-Guthaben, aktive Positionen, P&L-Tracking, Volumenmetriken und reichhaltigere Verbindungszustände",
        "💬 RelayChatSidebar — verbessertes Nachrichten-Rendering, Tipp-Indikatoren und Agenten-Pipeline-Anzeige",
        "🏠 DashboardPageClient — Live-Statistikabfragen und Echtzeit-Datenbindungen via React Query",
        "🔌 Providers — ReactQuery und SocketContext an der App-Wurzel für globalen Echtzeit-Zustand verdrahtet",
        "🔁 agentChat-Relay-Pipeline — vollständiges AURA→FLUX→CLAUSE→ORACLE→EDGE→LUCIFER→SIGMA-Streaming mit SSE und Token-Tracking pro Nachricht",
        "🔍 Markt-Scanner — Echtzeit-Scanning mit Kategorie-Tags, Vertrauens-Scoring und Polymarket-API-Integration",
        "⚖️ Risiko-Routen — verfeinerte Positionsgrößen-Logik und L3-Risikobewertungs-Endpunkte",
        "🧩 Verknüpfte Agenten-Hilfsprogramme — Pipeline-Verdrahtungs- und Auflösungs-Helfer aktualisiert",
      ],
    },
    fixes: {
      en: [
        "🎛️ AutopilotControlCard — toggle animation improvements and status feedback polish",
        "🔧 polymarket-prep service — better market data normalization, volume/liquidity enrichment, and error handling",
        "🗑️ db/seed.ts — removed legacy seed data, now fully handled by migrations",
        "📦 lib/api.ts + lib/dashboard.ts — new endpoint helpers for dashboard metrics",
        "🌐 i18n — all 4 locales (en/es/fr/de) updated with new translation keys for scanner and status cards",
      ],
      es: [
        "🎛️ AutopilotControlCard — mejoras en la animación del interruptor y pulido del feedback de estado",
        "🔧 Servicio polymarket-prep — mejor normalización de datos de mercado, enriquecimiento de volumen/liquidez y manejo de errores",
        "🗑️ db/seed.ts — datos de semilla heredados eliminados, ahora gestionados completamente por migraciones",
        "📦 lib/api.ts + lib/dashboard.ts — nuevos helpers de endpoints para métricas del dashboard",
        "🌐 i18n — los 4 idiomas (en/es/fr/de) actualizados con nuevas claves de traducción para tarjetas de escáner y estado",
      ],
      fr: [
        "🎛️ AutopilotControlCard — améliorations de l'animation du bouton et polissage du retour d'état",
        "🔧 Service polymarket-prep — meilleure normalisation des données de marché, enrichissement volume/liquidité et gestion des erreurs",
        "🗑️ db/seed.ts — données de seed legacy supprimées, maintenant entièrement gérées par les migrations",
        "📦 lib/api.ts + lib/dashboard.ts — nouveaux helpers d'endpoints pour les métriques du tableau de bord",
        "🌐 i18n — les 4 locales (en/es/fr/de) mises à jour avec de nouvelles clés de traduction pour les cartes scanner et statut",
      ],
      de: [
        "🎛️ AutopilotControlCard — Toggle-Animations-Verbesserungen und Status-Feedback-Politur",
        "🔧 polymarket-prep Service — bessere Marktdaten-Normalisierung, Volumen-/Liquiditäts-Anreicherung und Fehlerbehandlung",
        "🗑️ db/seed.ts — Legacy-Seed-Daten entfernt, jetzt vollständig durch Migrationen verwaltet",
        "📦 lib/api.ts + lib/dashboard.ts — neue Endpunkt-Helfer für Dashboard-Metriken",
        "🌐 i18n — alle 4 Lokalisierungen (en/es/fr/de) mit neuen Übersetzungsschlüsseln für Scanner- und Status-Karten aktualisiert",
      ],
    },
  },
  {
    version: "v1.1.0",
    released_at: "2026-03-12",
    highlight: {
      en: "Full i18n rollout, Polymarket status card, Playwright E2E migration, and component polish pass.",
      es: "Despliegue completo de i18n, tarjeta de estado de Polymarket, migración a Playwright E2E y pasada de pulido de componentes.",
      fr: "Déploiement complet de l'i18n, carte de statut Polymarket, migration vers Playwright E2E et passe de polissage des composants.",
      de: "Vollständige i18n-Einführung, Polymarket-Statuskarte, Playwright-E2E-Migration und Komponenten-Polier-Durchgang.",
    },
    features: {
      en: [
        "🌐 i18n migration — next-intl integrated across all dashboard pages; en, de, fr, es, pt locale files wired up",
        "📡 PolymarketStatusCard — live platform health indicator in sidebar showing API status, latency, and incident banner",
        "🎭 Playwright E2E — migrated all Cypress specs to Playwright; new CI steps with Clerk env injection",
        "🎨 Component polish pass — glass-morphism refinements, spacing consistency, and typography tuning across Manage Agent and Factory pages",
        "📋 Changelog panel i18n — title, labels, and version copy now fully translated via changelog message namespace",
      ],
      es: [
        "🌐 Migración i18n — next-intl integrado en todas las páginas del dashboard; archivos de idioma en, de, fr, es, pt configurados",
        "📡 PolymarketStatusCard — indicador de salud de la plataforma en vivo en la barra lateral mostrando estado de API, latencia y banner de incidentes",
        "🎭 Playwright E2E — migradas todas las especificaciones de Cypress a Playwright; nuevos pasos de CI con inyección de variables de Clerk",
        "🎨 Pasada de pulido de componentes — refinamientos de glassmorfismo, consistencia de espaciado y ajuste tipográfico en páginas de Gestión de Agente y Fábrica",
        "📋 Panel de changelog i18n — título, etiquetas y textos de versión ahora completamente traducidos vía namespace de mensajes changelog",
      ],
      fr: [
        "🌐 Migration i18n — next-intl intégré sur toutes les pages du tableau de bord ; fichiers de locale en, de, fr, es, pt configurés",
        "📡 PolymarketStatusCard — indicateur de santé de la plateforme en direct dans la barre latérale affichant le statut API, la latence et une bannière d'incident",
        "🎭 Playwright E2E — toutes les specs Cypress migrées vers Playwright ; nouvelles étapes CI avec injection des variables Clerk",
        "🎨 Passe de polissage des composants — raffinements glassmorphism, cohérence des espacements et réglage typographique sur les pages Gestion d'Agent et Usine",
        "📋 Panel changelog i18n — titre, labels et textes de version maintenant entièrement traduits via le namespace de messages changelog",
      ],
      de: [
        "🌐 i18n-Migration — next-intl auf allen Dashboard-Seiten integriert; en, de, fr, es, pt Locale-Dateien verdrahtet",
        "📡 PolymarketStatusCard — Live-Plattformzustand-Indikator in der Seitenleiste zeigt API-Status, Latenz und Incident-Banner",
        "🎭 Playwright E2E — alle Cypress-Specs zu Playwright migriert; neue CI-Schritte mit Clerk-Umgebungsvariablen-Injektion",
        "🎨 Komponenten-Polier-Durchgang — Glasmorphismus-Verfeinerungen, Abstands-Konsistenz und Typografie-Feinabstimmung auf Manage-Agent- und Factory-Seiten",
        "📋 Changelog-Panel i18n — Titel, Labels und Versionstexte jetzt vollständig über changelog-Nachrichten-Namespace übersetzt",
      ],
    },
    fixes: {
      en: [
        "🔧 Clerk env vars added to Playwright CI steps — specs were failing in GitHub Actions",
        "🗑️ Stale test-results artifacts removed from git tracking; .gitignore updated",
        "🧹 E2E suite cleaned up — removed outdated Cypress fixtures replaced by Playwright equivalents",
        "📦 Dashboard mission-rail, mini-map, and wallet checks added to Playwright coverage",
      ],
      es: [
        "🔧 Variables de entorno de Clerk agregadas a los pasos de CI de Playwright — las especificaciones fallaban en GitHub Actions",
        "🗑️ Artefactos obsoletos de test-results eliminados del seguimiento de git; .gitignore actualizado",
        "🧹 Suite E2E limpiada — eliminadas fixtures de Cypress desactualizadas reemplazadas por equivalentes de Playwright",
        "📦 Comprobaciones de mission-rail, mini-mapa y billetera del dashboard agregadas a la cobertura de Playwright",
      ],
      fr: [
        "🔧 Variables d'environnement Clerk ajoutées aux étapes CI Playwright — les specs échouaient dans GitHub Actions",
        "🗑️ Artefacts test-results obsolètes supprimés du suivi git ; .gitignore mis à jour",
        "🧹 Suite E2E nettoyée — fixtures Cypress obsolètes supprimées et remplacées par des équivalents Playwright",
        "📦 Vérifications mission-rail, mini-carte et portefeuille du tableau de bord ajoutées à la couverture Playwright",
      ],
      de: [
        "🔧 Clerk-Umgebungsvariablen zu Playwright-CI-Schritten hinzugefügt — Specs schlugen in GitHub Actions fehl",
        "🗑️ Veraltete test-results Artefakte aus git-Tracking entfernt; .gitignore aktualisiert",
        "🧹 E2E-Suite bereinigt — veraltete Cypress-Fixtures durch Playwright-Äquivalente ersetzt und entfernt",
        "📦 Dashboard mission-rail, Mini-Map und Wallet-Prüfungen zur Playwright-Abdeckung hinzugefügt",
      ],
    },
  },
  {
    version: "v1.0.0",
    released_at: "2026-03-09",
    highlight: {
      en: "BYO OpenClaw Agent, Agent World pixel environment, Architecture Viewer, onboarding flow, and full Manage Agent dashboard.",
      es: "Agente BYO OpenClaw, entorno pixel de Agent World, Visor de Arquitectura, flujo de incorporación y dashboard completo de Gestión de Agente.",
      fr: "Agent BYO OpenClaw, environnement pixel Agent World, Visionneuse d'Architecture, flux d'intégration et tableau de bord complet de Gestion d'Agent.",
      de: "BYO OpenClaw Agent, Agent World Pixel-Umgebung, Architektur-Viewer, Onboarding-Flow und vollständiges Manage-Agent-Dashboard.",
    },
    features: {
      en: [
        "🧩 BYO (Bring Your Own) Agent — full onboarding wizard with webhook config, wallet binding, and MCP server docs page",
        "🌍 Agent World — pixel-art Phaser 3 virtual environment with 7 NPC sub-agents, pathfinding, speech bubbles, dialogue system, and pipeline visualization",
        "🗺️ Architecture Viewer — interactive React Flow canvas showing full system topology (agents, services, data edges) with detail panels",
        "🤖 Manage Agent page — complete agent dashboard with identity header, health score, equity curve chart, live positions, metrics row, risk config, webhook panel, system log, and AI insights",
        "🏭 Agent Factory refactor — streamlined wizard flow with improved hooks, agent-limit enforcement, and BYO import path",
        "📡 Live agent status — replaced hardcoded agent badges with real /api/agent/status endpoint polling",
        "🚀 Autopilot Control Card — rich autopilot management UI with status indicators, quick actions, and webhook editor",
        "🎓 Onboarding modal — first-run autopilot setup guide with step-by-step activation flow",
        "📊 Agent limit UI — enforces max agent count with upgrade prompts in factory and sidebar",
        "🧪 Cypress E2E tests — new specs for BYO onboarding, agent factory wizard, and expanded autopilot coverage",
      ],
      es: [
        "🧩 Agente BYO (Traiga el Suyo) — asistente completo de incorporación con configuración de webhook, vinculación de billetera y página de documentación del servidor MCP",
        "🌍 Agent World — entorno virtual de arte pixel con Phaser 3, 7 sub-agentes NPC, búsqueda de caminos, globos de diálogo, sistema de conversación y visualización del pipeline",
        "🗺️ Visor de Arquitectura — canvas interactivo de React Flow que muestra la topología completa del sistema (agentes, servicios, bordes de datos) con paneles de detalle",
        "🤖 Página de Gestión de Agente — dashboard completo con encabezado de identidad, puntuación de salud, gráfico de curva de patrimonio, posiciones en vivo, fila de métricas, configuración de riesgo, panel de webhook, registro del sistema e información de IA",
        "🏭 Refactorización de Agent Factory — flujo de asistente optimizado con hooks mejorados, aplicación de límite de agentes y ruta de importación BYO",
        "📡 Estado de agente en vivo — badges de agente codificados reemplazados por sondeo real del endpoint /api/agent/status",
        "🚀 Tarjeta de Control de Autopiloto — rica UI de gestión de autopiloto con indicadores de estado, acciones rápidas y editor de webhook",
        "🎓 Modal de incorporación — guía de configuración de autopiloto en primer uso con flujo de activación paso a paso",
        "📊 UI de límite de agentes — aplica el número máximo de agentes con prompts de actualización en fábrica y barra lateral",
        "🧪 Tests E2E con Cypress — nuevas especificaciones para incorporación BYO, asistente de fábrica de agentes y cobertura ampliada de autopiloto",
      ],
      fr: [
        "🧩 Agent BYO (Apportez le Vôtre) — assistant d'intégration complet avec configuration webhook, liaison de portefeuille et page de documentation du serveur MCP",
        "🌍 Agent World — environnement virtuel pixel-art Phaser 3 avec 7 sous-agents PNJ, recherche de chemin, bulles de dialogue, système de conversation et visualisation du pipeline",
        "🗺️ Visionneuse d'Architecture — canvas React Flow interactif montrant la topologie complète du système (agents, services, arêtes de données) avec panneaux de détail",
        "🤖 Page de Gestion d'Agent — tableau de bord complet avec en-tête d'identité, score de santé, graphique de courbe d'équité, positions en direct, rangée de métriques, config de risque, panneau webhook, journal système et insights IA",
        "🏭 Refactorisation d'Agent Factory — flux d'assistant rationalisé avec hooks améliorés, application de limite d'agents et chemin d'importation BYO",
        "📡 Statut d'agent en direct — badges d'agents codés en dur remplacés par un sondage réel de l'endpoint /api/agent/status",
        "🚀 Carte de Contrôle Autopilote — interface riche de gestion autopilote avec indicateurs d'état, actions rapides et éditeur webhook",
        "🎓 Modal d'intégration — guide de configuration autopilote au premier démarrage avec flux d'activation étape par étape",
        "📊 UI de limite d'agents — applique le nombre maximum d'agents avec des invites de mise à niveau dans l'usine et la barre latérale",
        "🧪 Tests E2E Cypress — nouvelles specs pour l'intégration BYO, l'assistant de fabrique d'agents et couverture autopilote élargie",
      ],
      de: [
        "🧩 BYO (Bring Your Own) Agent — vollständiger Onboarding-Assistent mit Webhook-Konfiguration, Wallet-Bindung und MCP-Server-Dokumentationsseite",
        "🌍 Agent World — Pixel-Art Phaser 3 virtuelle Umgebung mit 7 NPC-Unteragenten, Pfadfindung, Sprechblasen, Dialogsystem und Pipeline-Visualisierung",
        "🗺️ Architektur-Viewer — interaktives React-Flow-Canvas mit vollständiger Systemtopologie (Agenten, Dienste, Datenkanten) und Detail-Panels",
        "🤖 Manage-Agent-Seite — vollständiges Agent-Dashboard mit Identitäts-Header, Gesundheitsscore, Eigenkapitalkurven-Diagramm, Live-Positionen, Metriken-Reihe, Risikokonfiguration, Webhook-Panel, Systemprotokoll und KI-Erkenntnissen",
        "🏭 Agent-Factory-Refactoring — optimierter Assistent-Flow mit verbesserten Hooks, Agentenlimit-Durchsetzung und BYO-Importpfad",
        "📡 Live-Agentstatus — hartcodierte Agenten-Badges durch echtes /api/agent/status Endpunkt-Polling ersetzt",
        "🚀 Autopilot-Steuerkarte — reichhaltige Autopilot-Management-UI mit Status-Indikatoren, Schnellaktionen und Webhook-Editor",
        "🎓 Onboarding-Modal — Erstauffahr-Autopilot-Setup-Guide mit schrittweisem Aktivierungsflow",
        "📊 Agentenlimit-UI — erzwingt maximale Agentenzahl mit Upgrade-Prompts in Factory und Seitenleiste",
        "🧪 Cypress E2E-Tests — neue Specs für BYO-Onboarding, Agent-Factory-Assistent und erweiterte Autopilot-Abdeckung",
      ],
    },
    fixes: {
      en: [
        "🔧 Agent Factory page refactored — extracted hooks, reduced component complexity by ~50%",
        "🗑️ Removed deprecated Autopilot standalone page (merged into Manage Agent)",
        "📦 Settings page simplified — agent config moved to dedicated Manage Agent panels",
        "🔗 BottomTabBar updated with agent factory badge and dynamic nav states",
        "🧹 normalizeAgentData handles all 7 backend agent field name mappings correctly",
        "📈 Equity curve chart fixed — handles missing data points gracefully",
        "🛡️ Webhook config panel validates URLs and shows delivery status",
      ],
      es: [
        "🔧 Página de Agent Factory refactorizada — hooks extraídos, complejidad de componentes reducida ~50%",
        "🗑️ Página independiente de Autopiloto obsoleta eliminada (fusionada en Gestión de Agente)",
        "📦 Página de configuración simplificada — configuración de agente movida a paneles dedicados de Gestión de Agente",
        "🔗 BottomTabBar actualizado con badge de fábrica de agentes y estados de navegación dinámicos",
        "🧹 normalizeAgentData maneja correctamente los 7 mapeos de nombres de campo del backend",
        "📈 Gráfico de curva de patrimonio corregido — maneja puntos de datos faltantes correctamente",
        "🛡️ Panel de configuración de webhook valida URLs y muestra el estado de entrega",
      ],
      fr: [
        "🔧 Page Agent Factory refactorisée — hooks extraits, complexité des composants réduite de ~50%",
        "🗑️ Page Autopilote autonome dépréciée supprimée (fusionnée dans Gestion d'Agent)",
        "📦 Page de paramètres simplifiée — config d'agent déplacée vers les panneaux dédiés de Gestion d'Agent",
        "🔗 BottomTabBar mis à jour avec badge de fabrique d'agents et états de navigation dynamiques",
        "🧹 normalizeAgentData gère correctement les 7 mappages de noms de champs backend",
        "📈 Graphique de courbe d'équité corrigé — gère gracieusement les points de données manquants",
        "🛡️ Le panneau de configuration webhook valide les URLs et affiche l'état de livraison",
      ],
      de: [
        "🔧 Agent-Factory-Seite refactoriert — Hooks extrahiert, Komponentenkomplexität um ~50% reduziert",
        "🗑️ Veraltete eigenständige Autopilot-Seite entfernt (in Manage Agent zusammengeführt)",
        "📦 Einstellungsseite vereinfacht — Agentenkonfiguration in dedizierte Manage-Agent-Panels verschoben",
        "🔗 BottomTabBar mit Agent-Factory-Badge und dynamischen Nav-Zuständen aktualisiert",
        "🧹 normalizeAgentData behandelt alle 7 Backend-Agenten-Feldnamen-Mappings korrekt",
        "📈 Eigenkapitalkurven-Diagramm behoben — fehlende Datenpunkte werden korrekt behandelt",
        "🛡️ Webhook-Konfigurationspanel validiert URLs und zeigt Lieferstatus an",
      ],
    },
  },
  {
    version: "v0.8.0",
    released_at: "2026-03-07",
    highlight: {
      en: "Clerk authentication, WDK wallet generation, real-time Socket.IO, Railway deployment, and full dashboard restructure.",
      es: "Autenticación con Clerk, generación de billetera WDK, Socket.IO en tiempo real, despliegue en Railway y reestructuración completa del dashboard.",
      fr: "Authentification Clerk, génération de portefeuille WDK, Socket.IO en temps réel, déploiement Railway et restructuration complète du tableau de bord.",
      de: "Clerk-Authentifizierung, WDK-Wallet-Generierung, Echtzeit-Socket.IO, Railway-Deployment und vollständige Dashboard-Umstrukturierung.",
    },
    features: {
      en: [
        "🔐 Clerk authentication — sign-in/sign-up pages, JWT sync, UserButton in sidebar, middleware route protection",
        "👛 WDK wallet generation — real EVM wallets via Tether WDK in Agent Factory Step 5, private key download as .txt",
        "⚡ Socket.IO real-time events — trade:executed, agent:alert, autopilot:status, position:updated with per-user rooms",
        "🔔 Browser trade notifications — push alerts when tab is backgrounded via useTradeNotifications hook",
        "🏗️ Dashboard layout restructure — all pages moved under app/(dashboard) with shared layout, sidebar, and top bar",
        "🌐 Marketing landing page — public homepage at app/(marketing)/page.tsx with product showcase",
        "🤖 Personalized agent chat — agent personality-aware responses, system prompt from wizard, SSE streaming",
        "🛠️ Agent tool calling — 7 tools (portfolio, risk, history, markets, analysis, trade, signals) via Gemini function calling",
        "🚂 Railway deployment — PostgreSQL, Redis, BullMQ, full infra provisioning with private networking",
        "🔒 API key encryption — AES-256-GCM for stored secrets, prompt injection defense in agent chat",
        "🗄️ PostgreSQL dual-driver — production Postgres with SQLite fallback, 30+ table migration",
        "📡 Redis + BullMQ job queues — scanner, orchestrator, hot scanner, fill monitor, PnL settler, alert poller",
      ],
      es: [
        "🔐 Autenticación Clerk — páginas de inicio/registro de sesión, sincronización JWT, UserButton en la barra lateral, protección de rutas por middleware",
        "👛 Generación de billetera WDK — billeteras EVM reales vía Tether WDK en el Paso 5 de Agent Factory, descarga de clave privada como .txt",
        "⚡ Eventos en tiempo real de Socket.IO — trade:executed, agent:alert, autopilot:status, position:updated con salas por usuario",
        "🔔 Notificaciones de trades del navegador — alertas push cuando la pestaña está en segundo plano vía hook useTradeNotifications",
        "🏗️ Reestructuración del layout del dashboard — todas las páginas movidas bajo app/(dashboard) con layout compartido, barra lateral y barra superior",
        "🌐 Página de aterrizaje de marketing — página de inicio pública en app/(marketing)/page.tsx con presentación del producto",
        "🤖 Chat de agente personalizado — respuestas con personalidad del agente, prompt del sistema desde el asistente, streaming SSE",
        "🛠️ Llamada de herramientas del agente — 7 herramientas (cartera, riesgo, historial, mercados, análisis, trade, señales) vía función calling de Gemini",
        "🚂 Despliegue en Railway — PostgreSQL, Redis, BullMQ, aprovisionamiento completo de infraestructura con redes privadas",
        "🔒 Cifrado de clave API — AES-256-GCM para secretos almacenados, defensa contra inyección de prompts en el chat del agente",
        "🗄️ Doble driver PostgreSQL — Postgres de producción con respaldo SQLite, migración de 30+ tablas",
        "📡 Colas de trabajo Redis + BullMQ — escáner, orquestador, escáner en caliente, monitor de relleno, liquidador PnL, sondeador de alertas",
      ],
      fr: [
        "🔐 Authentification Clerk — pages de connexion/inscription, sync JWT, UserButton dans la barre latérale, protection des routes par middleware",
        "👛 Génération de portefeuille WDK — vrais portefeuilles EVM via Tether WDK à l'Étape 5 d'Agent Factory, téléchargement de clé privée en .txt",
        "⚡ Événements temps réel Socket.IO — trade:executed, agent:alert, autopilot:status, position:updated avec des salles par utilisateur",
        "🔔 Notifications de trades du navigateur — alertes push quand l'onglet est en arrière-plan via le hook useTradeNotifications",
        "🏗️ Restructuration du layout du tableau de bord — toutes les pages déplacées sous app/(dashboard) avec layout partagé, barre latérale et barre du haut",
        "🌐 Page d'accueil marketing — page d'accueil publique sur app/(marketing)/page.tsx avec présentation du produit",
        "🤖 Chat d'agent personnalisé — réponses avec la personnalité de l'agent, prompt système depuis l'assistant, streaming SSE",
        "🛠️ Appel d'outils de l'agent — 7 outils (portefeuille, risque, historique, marchés, analyse, trade, signaux) via Gemini function calling",
        "🚂 Déploiement Railway — PostgreSQL, Redis, BullMQ, provisionnement complet de l'infra avec réseau privé",
        "🔒 Chiffrement des clés API — AES-256-GCM pour les secrets stockés, défense contre l'injection de prompts dans le chat",
        "🗄️ Double driver PostgreSQL — Postgres de production avec fallback SQLite, migration de 30+ tables",
        "📡 Files de travail Redis + BullMQ — scanner, orchestrateur, scanner chaud, moniteur de remplissage, liquidateur PnL, sondeur d'alertes",
      ],
      de: [
        "🔐 Clerk-Authentifizierung — Anmelde-/Registrierungsseiten, JWT-Sync, UserButton in der Seitenleiste, Middleware-Routenschutz",
        "👛 WDK-Wallet-Generierung — echte EVM-Wallets via Tether WDK in Agent-Factory Schritt 5, privater Schlüssel-Download als .txt",
        "⚡ Socket.IO-Echtzeitereignisse — trade:executed, agent:alert, autopilot:status, position:updated mit benutzerspezifischen Räumen",
        "🔔 Browser-Trade-Benachrichtigungen — Push-Alerts wenn Tab im Hintergrund via useTradeNotifications-Hook",
        "🏗️ Dashboard-Layout-Umstrukturierung — alle Seiten unter app/(dashboard) mit gemeinsamem Layout, Seitenleiste und Topbar verschoben",
        "🌐 Marketing-Landingpage — öffentliche Homepage unter app/(marketing)/page.tsx mit Produktpräsentation",
        "🤖 Personalisierter Agenten-Chat — agentenpersönlichkeitsbewusste Antworten, System-Prompt vom Assistenten, SSE-Streaming",
        "🛠️ Agenten-Tool-Calling — 7 Tools (Portfolio, Risiko, Historie, Märkte, Analyse, Trade, Signale) via Gemini Function Calling",
        "🚂 Railway-Deployment — PostgreSQL, Redis, BullMQ, vollständige Infra-Provisionierung mit privatem Networking",
        "🔒 API-Key-Verschlüsselung — AES-256-GCM für gespeicherte Secrets, Prompt-Injection-Schutz im Agenten-Chat",
        "🗄️ PostgreSQL Dual-Treiber — Produktions-Postgres mit SQLite-Fallback, 30+ Tabellen-Migration",
        "📡 Redis + BullMQ Job-Queues — Scanner, Orchestrator, Hot-Scanner, Fill-Monitor, PnL-Abrechner, Alert-Poller",
      ],
    },
    fixes: {
      en: [
        "🧹 Removed deprecated ActivePositions and PortfolioOverview components",
        "🔗 Market links now route correctly under (dashboard) group",
        "📊 Trade history API source updated to use authenticated endpoint",
        "🧪 All Cypress and Playwright e2e specs updated for new route structure",
        "🛡️ Clerk middleware protects dashboard routes, public routes remain accessible",
        "📦 Providers component refactored — ClerkProvider, SocketProvider, QueryClient, PaperMode all unified",
      ],
      es: [
        "🧹 Componentes obsoletos ActivePositions y PortfolioOverview eliminados",
        "🔗 Los enlaces de mercado ahora enrutan correctamente bajo el grupo (dashboard)",
        "📊 Fuente de API de historial de trades actualizada para usar el endpoint autenticado",
        "🧪 Todas las especificaciones e2e de Cypress y Playwright actualizadas para la nueva estructura de rutas",
        "🛡️ El middleware de Clerk protege las rutas del dashboard, las rutas públicas permanecen accesibles",
        "📦 Componente Providers refactorizado — ClerkProvider, SocketProvider, QueryClient, PaperMode todos unificados",
      ],
      fr: [
        "🧹 Composants obsolètes ActivePositions et PortfolioOverview supprimés",
        "🔗 Les liens de marché routent maintenant correctement sous le groupe (dashboard)",
        "📊 Source de l'API d'historique des trades mise à jour pour utiliser l'endpoint authentifié",
        "🧪 Toutes les specs e2e Cypress et Playwright mises à jour pour la nouvelle structure de routes",
        "🛡️ Le middleware Clerk protège les routes du tableau de bord, les routes publiques restent accessibles",
        "📦 Composant Providers refactorisé — ClerkProvider, SocketProvider, QueryClient, PaperMode tous unifiés",
      ],
      de: [
        "🧹 Veraltete ActivePositions und PortfolioOverview Komponenten entfernt",
        "🔗 Markt-Links routen nun korrekt unter (dashboard) Gruppe",
        "📊 Trade-Historien-API-Quelle auf authentifizierten Endpunkt aktualisiert",
        "🧪 Alle Cypress und Playwright E2E-Specs für neue Routenstruktur aktualisiert",
        "🛡️ Clerk-Middleware schützt Dashboard-Routen, öffentliche Routen bleiben zugänglich",
        "📦 Providers-Komponente refactoriert — ClerkProvider, SocketProvider, QueryClient, PaperMode alle vereinheitlicht",
      ],
    },
  },
  {
    version: "v0.7.0",
    released_at: "2026-03-07",
    highlight: {
      en: "Agent Factory wizard, skeleton loading system, and Arena prototype.",
      es: "Asistente de Agent Factory, sistema de carga esqueleto y prototipo de Arena.",
      fr: "Assistant Agent Factory, système de chargement squelette et prototype Arena.",
      de: "Agent-Factory-Assistent, Skeleton-Ladesystem und Arena-Prototyp.",
    },
    features: {
      en: [
        "🏭 Agent Factory page — multi-step wizard to configure custom trading agents (identity, strategy, risk, preferences)",
        "💀 Skeleton loading placeholders across all major pages — markets, dashboard, portfolio, trade history, settings, reports",
        "📦 Skeleton shimmer components added to ExecutionLog, PerformancePanel, PnlTicker, PortfolioOverview, RecentSignals",
        "🕹️ Arena page prototype — Agent Battle Royale concept with multiplayer evolutionary trading (replaced by Agent Factory in nav)",
        "🧱 Reusable Skeleton UI primitive component for consistent loading states",
      ],
      es: [
        "🏭 Página de Agent Factory — asistente de múltiples pasos para configurar agentes de trading personalizados (identidad, estrategia, riesgo, preferencias)",
        "💀 Marcadores de posición de carga esqueleto en todas las páginas principales — mercados, dashboard, cartera, historial de trades, configuración, informes",
        "📦 Componentes shimmer de esqueleto agregados a ExecutionLog, PerformancePanel, PnlTicker, PortfolioOverview, RecentSignals",
        "🕹️ Prototipo de página Arena — concepto de Battle Royale de Agentes con trading evolutivo multijugador (reemplazado por Agent Factory en la navegación)",
        "🧱 Componente UI primitivo Skeleton reutilizable para estados de carga consistentes",
      ],
      fr: [
        "🏭 Page Agent Factory — assistant multi-étapes pour configurer des agents de trading personnalisés (identité, stratégie, risque, préférences)",
        "💀 Placeholders de chargement squelette sur toutes les pages principales — marchés, tableau de bord, portfolio, historique des trades, paramètres, rapports",
        "📦 Composants shimmer squelette ajoutés à ExecutionLog, PerformancePanel, PnlTicker, PortfolioOverview, RecentSignals",
        "🕹️ Prototype de page Arena — concept de Battle Royale d'agents avec trading évolutif multijoueur (remplacé par Agent Factory dans la nav)",
        "🧱 Composant UI primitif Skeleton réutilisable pour des états de chargement cohérents",
      ],
      de: [
        "🏭 Agent-Factory-Seite — mehrstufiger Assistent zur Konfiguration benutzerdefinierter Trading-Agenten (Identität, Strategie, Risiko, Präferenzen)",
        "💀 Skeleton-Lade-Platzhalter auf allen Hauptseiten — Märkte, Dashboard, Portfolio, Trade-Historie, Einstellungen, Berichte",
        "📦 Skeleton-Shimmer-Komponenten zu ExecutionLog, PerformancePanel, PnlTicker, PortfolioOverview, RecentSignals hinzugefügt",
        "🕹️ Arena-Seiten-Prototyp — Agent Battle Royale Konzept mit Multiplayer-Evolutionshandel (durch Agent Factory in Nav ersetzt)",
        "🧱 Wiederverwendbare Skeleton-UI-Primitive-Komponente für konsistente Ladezustände",
      ],
    },
    fixes: {
      en: [
        "🧭 Sidebar nav reorganized — Arena removed, Agent Factory added between Autopilot and Settings",
        "🗑️ Deprecated ActivePositions component cleaned up",
        "🔄 Resilient polling and loading/error states added to risk, orchestrator, and status panels",
        "⚡ PnlTicker removed from autopilot page to reduce layout noise",
      ],
      es: [
        "🧭 Navegación de barra lateral reorganizada — Arena eliminado, Agent Factory agregado entre Autopiloto y Configuración",
        "🗑️ Componente ActivePositions obsoleto limpiado",
        "🔄 Sondeo resiliente y estados de carga/error agregados a los paneles de riesgo, orquestador y estado",
        "⚡ PnlTicker eliminado de la página de autopiloto para reducir el ruido del diseño",
      ],
      fr: [
        "🧭 Navigation de la barre latérale réorganisée — Arena supprimé, Agent Factory ajouté entre Autopilote et Paramètres",
        "🗑️ Composant ActivePositions déprécié nettoyé",
        "🔄 Sondage résilient et états de chargement/erreur ajoutés aux panneaux de risque, d'orchestrateur et de statut",
        "⚡ PnlTicker supprimé de la page autopilote pour réduire le bruit de mise en page",
      ],
      de: [
        "🧭 Seitenleisten-Navigation reorganisiert — Arena entfernt, Agent Factory zwischen Autopilot und Einstellungen hinzugefügt",
        "🗑️ Veraltete ActivePositions-Komponente bereinigt",
        "🔄 Resilientes Polling und Lade-/Fehlerzustände zu Risiko-, Orchestrator- und Status-Panels hinzugefügt",
        "⚡ PnlTicker von Autopilot-Seite entfernt um Layout-Rauschen zu reduzieren",
      ],
    },
  },
  {
    version: "v0.6.0",
    released_at: "2026-03-06",
    highlight: {
      en: "Market page & agent pipeline overhaul with animated visualizations and real order book data.",
      es: "Renovación de la página de mercado y el pipeline de agentes con visualizaciones animadas y datos reales del libro de órdenes.",
      fr: "Refonte de la page de marché et du pipeline d'agents avec des visualisations animées et des données réelles du carnet d'ordres.",
      de: "Marktseite & Agenten-Pipeline-Überarbeitung mit animierten Visualisierungen und echten Orderbuch-Daten.",
    },
    features: {
      en: [
        "🎨 Full /market/[slug] redesign — chart + live order book two-column layout",
        "🤖 Animated agent cards: Aura semicircle gauge, Flux spread bar, Oracle dual-ring, Confidence bar all animate on mount",
        "⭕ Oracle probability ring — dual concentric rings showing model vs market-implied with edge delta in center",
        "💬 Synthesized Insight via Relay LLM — plain-English one-sentence summary streamed in real time",
        "📖 Real order book data from backend — live bids/asks with depth bars, 10s auto-refresh",
        "⏱️ Pipeline timeline shows real per-agent latency from store",
        "💰 Alpha Signal bankroll reads from live on-chain USDC wallet balance",
      ],
      es: [
        "🎨 Rediseño completo de /market/[slug] — diseño de dos columnas con gráfico + libro de órdenes en vivo",
        "🤖 Tarjetas de agentes animadas: medidor semicircular Aura, barra de spread Flux, anillo dual Oracle, barra de Confianza animados al montar",
        "⭕ Anillo de probabilidad Oracle — anillos concéntricos duales mostrando modelo vs mercado implícito con delta de ventaja en el centro",
        "💬 Perspectiva sintetizada vía Relay LLM — resumen en inglés claro de una oración transmitido en tiempo real",
        "📖 Datos reales del libro de órdenes del backend — bids/asks en vivo con barras de profundidad, actualización automática cada 10s",
        "⏱️ La línea de tiempo del pipeline muestra la latencia real por agente desde el store",
        "💰 El bankroll de Alpha Signal lee el saldo de billetera USDC en cadena en tiempo real",
      ],
      fr: [
        "🎨 Redesign complet de /market/[slug] — mise en page deux colonnes avec graphique + carnet d'ordres en direct",
        "🤖 Cartes d'agents animées : jauge semicirculaire Aura, barre de spread Flux, anneau dual Oracle, barre de Confiance animés au montage",
        "⭕ Anneau de probabilité Oracle — anneaux concentriques doubles montrant le modèle vs l'implicite du marché avec le delta d'avantage au centre",
        "💬 Insight synthétisé via Relay LLM — résumé en une phrase en langage clair diffusé en temps réel",
        "📖 Données réelles du carnet d'ordres depuis le backend — bids/asks en direct avec barres de profondeur, rafraîchissement auto toutes les 10s",
        "⏱️ La timeline du pipeline affiche la latence réelle par agent depuis le store",
        "💰 Le bankroll Alpha Signal lit le solde du portefeuille USDC on-chain en temps réel",
      ],
      de: [
        "🎨 Vollständiges /market/[slug] Redesign — Zweispalten-Layout mit Diagramm + Live-Orderbuch",
        "🤖 Animierte Agentenkarten: Aura-Halbkreisgauge, Flux-Spread-Balken, Oracle-Doppelring, Konfidenzbalken animieren beim Mounten",
        "⭕ Oracle-Wahrscheinlichkeitsring — doppelte konzentrische Ringe zeigen Modell vs. marktimpliziert mit Edge-Delta in der Mitte",
        "💬 Synthetisierter Einblick via Relay LLM — klare einzeilige Zusammenfassung in Echtzeit gestreamt",
        "📖 Echte Orderbuch-Daten vom Backend — Live-Bids/Asks mit Tiefen-Balken, 10s Auto-Aktualisierung",
        "⏱️ Pipeline-Timeline zeigt echte Pro-Agenten-Latenz aus dem Store",
        "💰 Alpha-Signal-Bankroll liest vom Live-On-Chain-USDC-Wallet-Guthaben",
      ],
    },
    fixes: {
      en: [
        "🐛 Cent sign ¢ was rendering as literal \\u00A2 in SigmaDecision — fixed",
        "📌 HelpTooltip clipping on right side of screen — now uses createPortal to document.body with viewport clamping",
        "🔢 Pipeline timeline bars were all 1s — was hardcoded fallback, now uses real latencyMs from store",
        "📦 iconoir-react package was missing — replaced with inline SVG in HelpTooltip",
        "🗑️ Removed /market-analysis page and its sidebar nav entry",
        "📈 Main price chart no longer re-animates on every pipeline run",
      ],
      es: [
        "🐛 El signo de centavo ¢ se renderizaba como \\u00A2 literal en SigmaDecision — corregido",
        "📌 HelpTooltip recortado en el lado derecho de la pantalla — ahora usa createPortal a document.body con sujeción de viewport",
        "🔢 Las barras de la línea de tiempo del pipeline eran todas 1s — era un fallback codificado, ahora usa latencyMs real del store",
        "📦 Paquete iconoir-react faltaba — reemplazado con SVG inline en HelpTooltip",
        "🗑️ Página /market-analysis y su entrada en la navegación lateral eliminadas",
        "📈 El gráfico de precios principal ya no se reanima en cada ejecución del pipeline",
      ],
      fr: [
        "🐛 Le signe centavo ¢ s'affichait comme \\u00A2 littéral dans SigmaDecision — corrigé",
        "📌 HelpTooltip coupé sur le côté droit de l'écran — utilise maintenant createPortal vers document.body avec clamping de viewport",
        "🔢 Les barres de la timeline du pipeline étaient toutes à 1s — c'était un fallback codé en dur, utilise maintenant le vrai latencyMs du store",
        "📦 Le package iconoir-react manquait — remplacé par du SVG inline dans HelpTooltip",
        "🗑️ Page /market-analysis et son entrée de navigation latérale supprimées",
        "📈 Le graphique de prix principal ne se réanime plus à chaque exécution du pipeline",
      ],
      de: [
        "🐛 Cent-Zeichen ¢ wurde als literales \\u00A2 in SigmaDecision gerendert — behoben",
        "📌 HelpTooltip wird auf der rechten Bildschirmseite abgeschnitten — verwendet jetzt createPortal zu document.body mit Viewport-Clamping",
        "🔢 Pipeline-Timeline-Balken waren alle 1s — war hartcodierter Fallback, verwendet jetzt echte latencyMs aus dem Store",
        "📦 iconoir-react Paket fehlte — durch inline SVG in HelpTooltip ersetzt",
        "🗑️ /market-analysis Seite und ihr Seitenleisten-Nav-Eintrag entfernt",
        "📈 Haupt-Preisdiagramm animiert sich nicht mehr bei jedem Pipeline-Lauf neu",
      ],
    },
  },
  {
    version: "v0.5.0",
    released_at: "2026-02-20",
    highlight: {
      en: "Dashboard real data binding, performance metrics, and tooltip system.",
      es: "Vinculación de datos reales del dashboard, métricas de rendimiento y sistema de tooltips.",
      fr: "Liaison de données réelles du tableau de bord, métriques de performance et système de tooltips.",
      de: "Dashboard-Echtdatenbindung, Leistungsmetriken und Tooltip-System.",
    },
    features: {
      en: [
        "📊 Dashboard fully wired to real API — PnL, USDC, POL balances, total value",
        "🏆 Win rate ring visualization in performance panel",
        "📈 Enriched performance metrics — Brier scores, attribution, drift status",
        "🔔 Telegram webhook editor in autopilot settings",
        "❓ HelpTooltip component system across all dashboard section headers",
        "🛡️ Risk Limits panel with live circuit breaker status and Kelly utilization",
      ],
      es: [
        "📊 Dashboard completamente conectado a la API real — PnL, USDC, saldos POL, valor total",
        "🏆 Visualización de anillo de tasa de victorias en el panel de rendimiento",
        "📈 Métricas de rendimiento enriquecidas — puntuaciones Brier, atribución, estado de deriva",
        "🔔 Editor de webhook de Telegram en la configuración del autopiloto",
        "❓ Sistema de componentes HelpTooltip en todos los encabezados de sección del dashboard",
        "🛡️ Panel de límites de riesgo con estado del interruptor de circuito en vivo y utilización de Kelly",
      ],
      fr: [
        "📊 Tableau de bord entièrement connecté à l'API réelle — PnL, USDC, soldes POL, valeur totale",
        "🏆 Visualisation en anneau du taux de victoires dans le panneau de performance",
        "📈 Métriques de performance enrichies — scores Brier, attribution, statut de dérive",
        "🔔 Éditeur webhook Telegram dans les paramètres de l'autopilote",
        "❓ Système de composants HelpTooltip sur tous les en-têtes de section du tableau de bord",
        "🛡️ Panneau de limites de risque avec statut du disjoncteur en direct et utilisation de Kelly",
      ],
      de: [
        "📊 Dashboard vollständig mit echter API verbunden — PnL, USDC, POL-Guthaben, Gesamtwert",
        "🏆 Win-Rate-Ring-Visualisierung im Performance-Panel",
        "📈 Angereicherte Leistungsmetriken — Brier-Scores, Attribution, Drift-Status",
        "🔔 Telegram-Webhook-Editor in Autopilot-Einstellungen",
        "❓ HelpTooltip-Komponentensystem auf allen Dashboard-Abschnitts-Headern",
        "🛡️ Risikolimiten-Panel mit Live-Leistungsschalter-Status und Kelly-Auslastung",
      ],
    },
    fixes: {
      en: [
        "🔧 WalletBalance interface updated with onChainUsdc and pol fields",
        "👁️ Active Positions panel was hidden due to empty state logic — fixed",
        "🔄 normalizeAgentData now maps backend field names to frontend types",
        "♻️ Risk status duplicated on dashboard — removed duplicate panel",
        "🛠️ CI build failures fixed for PerformancePanel and HelpTooltip imports",
        "💡 Scanner feed handles object response from /api/pipeline/results",
      ],
      es: [
        "🔧 Interfaz WalletBalance actualizada con campos onChainUsdc y pol",
        "👁️ El panel de Posiciones Activas estaba oculto debido a la lógica de estado vacío — corregido",
        "🔄 normalizeAgentData ahora mapea los nombres de campo del backend a los tipos del frontend",
        "♻️ Estado de riesgo duplicado en el dashboard — panel duplicado eliminado",
        "🛠️ Fallos de compilación de CI corregidos para las importaciones de PerformancePanel y HelpTooltip",
        "💡 El feed del escáner maneja la respuesta de objeto de /api/pipeline/results",
      ],
      fr: [
        "🔧 Interface WalletBalance mise à jour avec les champs onChainUsdc et pol",
        "👁️ Le panneau Positions Actives était masqué à cause de la logique d'état vide — corrigé",
        "🔄 normalizeAgentData mappe maintenant les noms de champs backend vers les types frontend",
        "♻️ Statut de risque dupliqué sur le tableau de bord — panneau dupliqué supprimé",
        "🛠️ Échecs de build CI corrigés pour les imports de PerformancePanel et HelpTooltip",
        "💡 Le feed du scanner gère la réponse objet de /api/pipeline/results",
      ],
      de: [
        "🔧 WalletBalance-Interface mit onChainUsdc und pol Feldern aktualisiert",
        "👁️ Aktive-Positionen-Panel war aufgrund leerer Zustandslogik versteckt — behoben",
        "🔄 normalizeAgentData mappt jetzt Backend-Feldnamen auf Frontend-Typen",
        "♻️ Risikostatus auf Dashboard dupliziert — dupliziertes Panel entfernt",
        "🛠️ CI-Build-Fehler für PerformancePanel und HelpTooltip Imports behoben",
        "💡 Scanner-Feed verarbeitet Objekt-Antwort von /api/pipeline/results",
      ],
    },
  },
  {
    version: "v0.4.0",
    released_at: "2026-02-05",
    highlight: {
      en: "Relay AI chat with SSE streaming, autopilot dashboard, and changelog panel.",
      es: "Chat de IA Relay con streaming SSE, dashboard de autopiloto y panel de changelog.",
      fr: "Chat IA Relay avec streaming SSE, tableau de bord autopilote et panel de changelog.",
      de: "Relay-KI-Chat mit SSE-Streaming, Autopilot-Dashboard und Changelog-Panel.",
    },
    features: {
      en: [
        "🤝 Relay SSE streaming — word-by-word token delivery, ~250ms TTFT",
        "💬 Suggested question pills shown after every Relay response",
        "⌨️ Relay typing indicator with animated dot pulse",
        "⚡ Autopilot dashboard — scanner feed, execution log, live P&L ticker, status bar",
        "📋 This changelog panel — version history accessible from sidebar",
        "📱 Relay chat sidebar with glassmorphism drawer overlay",
      ],
      es: [
        "🤝 Streaming SSE de Relay — entrega de tokens palabra por palabra, ~250ms TTFT",
        "💬 Píldoras de preguntas sugeridas mostradas después de cada respuesta de Relay",
        "⌨️ Indicador de escritura de Relay con pulso de punto animado",
        "⚡ Dashboard de autopiloto — feed del escáner, registro de ejecución, ticker P&L en vivo, barra de estado",
        "📋 Este panel de changelog — historial de versiones accesible desde la barra lateral",
        "📱 Barra lateral de chat Relay con superposición de cajón glassmorfismo",
      ],
      fr: [
        "🤝 Streaming SSE de Relay — livraison de tokens mot par mot, ~250ms TTFT",
        "💬 Pilules de questions suggérées affichées après chaque réponse de Relay",
        "⌨️ Indicateur de frappe Relay avec impulsion de point animé",
        "⚡ Tableau de bord autopilote — feed du scanner, journal d'exécution, ticker P&L en direct, barre de statut",
        "📋 Ce panel de changelog — historique des versions accessible depuis la barre latérale",
        "📱 Barre latérale de chat Relay avec superposition de tiroir glassmorphism",
      ],
      de: [
        "🤝 Relay SSE-Streaming — Wort-für-Wort Token-Lieferung, ~250ms TTFT",
        "💬 Vorgeschlagene Fragen-Pills nach jeder Relay-Antwort angezeigt",
        "⌨️ Relay-Tipp-Indikator mit animiertem Punkt-Puls",
        "⚡ Autopilot-Dashboard — Scanner-Feed, Ausführungsprotokoll, Live-P&L-Ticker, Statusleiste",
        "📋 Dieses Changelog-Panel — Versionsverlauf über Seitenleiste zugänglich",
        "📱 Relay-Chat-Seitenleiste mit Glasmorphismus-Drawer-Overlay",
      ],
    },
    fixes: {
      en: [
        "🤖 Relay model name corrected to Gemini 2.5 Flash, badge updated",
        "📱 Mobile keyboard layout broke Relay input — viewport-fit cover fix applied",
        "🧭 Suggested questions were disappearing — now always visible after response",
        "🔄 Relay suggested questions now rotate stably without index drift",
      ],
      es: [
        "🤖 Nombre del modelo Relay corregido a Gemini 2.5 Flash, badge actualizado",
        "📱 El diseño del teclado móvil rompía la entrada de Relay — se aplicó corrección de cubierta viewport-fit",
        "🧭 Las preguntas sugeridas desaparecían — ahora siempre visibles después de la respuesta",
        "🔄 Las preguntas sugeridas de Relay ahora rotan de manera estable sin deriva de índice",
      ],
      fr: [
        "🤖 Nom du modèle Relay corrigé en Gemini 2.5 Flash, badge mis à jour",
        "📱 La mise en page du clavier mobile cassait la saisie Relay — correction viewport-fit cover appliquée",
        "🧭 Les questions suggérées disparaissaient — maintenant toujours visibles après la réponse",
        "🔄 Les questions suggérées de Relay tournent maintenant de manière stable sans dérive d'index",
      ],
      de: [
        "🤖 Relay-Modellname auf Gemini 2.5 Flash korrigiert, Badge aktualisiert",
        "📱 Mobile Tastatur-Layout brach Relay-Eingabe — viewport-fit cover Fix angewendet",
        "🧭 Vorgeschlagene Fragen verschwanden — jetzt immer nach Antwort sichtbar",
        "🔄 Relay vorgeschlagene Fragen rotieren jetzt stabil ohne Index-Drift",
      ],
    },
  },
  {
    version: "v0.3.0",
    released_at: "2026-01-22",
    highlight: {
      en: "Full pipeline engine, live agent cards, trade execution, and risk management.",
      es: "Motor de pipeline completo, tarjetas de agentes en vivo, ejecución de trades y gestión de riesgos.",
      fr: "Moteur de pipeline complet, cartes d'agents en direct, exécution de trades et gestion des risques.",
      de: "Vollständige Pipeline-Engine, Live-Agentenkarten, Trade-Ausführung und Risikomanagement.",
    },
    features: {
      en: [
        "🚀 Market page rebuilt from scratch — live SSE pipeline log, Terminal-style design",
        "💸 Execute Trade wired to /api/execution/order with trade confirmation modal",
        "⚠️ Risk panel — circuit breaker status, live exposure, Kelly utilization limits",
        "📊 Performance panel — Brier scores, attribution breakdown, drift status",
        "🔄 Live SSE pipeline feed with per-agent card updates and status transitions",
        "🧪 Full Cypress E2E test suite for pipeline, signals, and trade flow",
      ],
      es: [
        "🚀 Página de mercado reconstruida desde cero — registro de pipeline SSE en vivo, diseño estilo Terminal",
        "💸 Ejecutar Trade conectado a /api/execution/order con modal de confirmación de trade",
        "⚠️ Panel de riesgo — estado del interruptor de circuito, exposición en vivo, límites de utilización de Kelly",
        "📊 Panel de rendimiento — puntuaciones Brier, desglose de atribución, estado de deriva",
        "🔄 Feed de pipeline SSE en vivo con actualizaciones de tarjetas por agente y transiciones de estado",
        "🧪 Suite completa de pruebas E2E con Cypress para pipeline, señales y flujo de trades",
      ],
      fr: [
        "🚀 Page de marché reconstruite de zéro — journal de pipeline SSE en direct, design style Terminal",
        "💸 Exécuter Trade connecté à /api/execution/order avec modal de confirmation de trade",
        "⚠️ Panneau de risque — statut du disjoncteur, exposition en direct, limites d'utilisation de Kelly",
        "📊 Panneau de performance — scores Brier, décomposition de l'attribution, statut de dérive",
        "🔄 Feed de pipeline SSE en direct avec mises à jour des cartes par agent et transitions d'état",
        "🧪 Suite complète de tests E2E Cypress pour le pipeline, les signaux et le flux de trades",
      ],
      de: [
        "🚀 Marktseite von Grund auf neu gebaut — Live-SSE-Pipeline-Protokoll, Terminal-Stil-Design",
        "💸 Trade ausführen an /api/execution/order verdrahtet mit Trade-Bestätigungs-Modal",
        "⚠️ Risiko-Panel — Leistungsschalter-Status, Live-Exposition, Kelly-Auslastungslimits",
        "📊 Performance-Panel — Brier-Scores, Attributions-Aufschlüsselung, Drift-Status",
        "🔄 Live-SSE-Pipeline-Feed mit Pro-Agenten-Karten-Updates und Statusübergängen",
        "🧪 Vollständige Cypress-E2E-Testsuite für Pipeline, Signale und Trade-Flow",
      ],
    },
    fixes: {
      en: [
        "🛠️ PipelineLog rewritten — no more stale closures, reliable event queue drainer",
        "📡 SSE event parsing fixed — agent cards now update correctly on pipeline run",
        "📈 Price chart uses clobTokenIds[0] as tokenId — was using wrong field",
        "🔒 CircuitBreaker API response normalized — handles object and string shapes",
        "💥 toFixed crash on pipeline run — Number() coercion added to all numeric fields",
      ],
      es: [
        "🛠️ PipelineLog reescrito — sin más closures obsoletos, drenador de cola de eventos confiable",
        "📡 Análisis de eventos SSE corregido — las tarjetas de agentes ahora se actualizan correctamente en la ejecución del pipeline",
        "📈 El gráfico de precios usa clobTokenIds[0] como tokenId — estaba usando el campo incorrecto",
        "🔒 Respuesta API de CircuitBreaker normalizada — maneja formas de objeto y cadena",
        "💥 Fallo de toFixed en la ejecución del pipeline — coerción Number() agregada a todos los campos numéricos",
      ],
      fr: [
        "🛠️ PipelineLog réécrit — plus de closures périmées, videur de file d'événements fiable",
        "📡 Analyse des événements SSE corrigée — les cartes d'agents se mettent maintenant à jour correctement lors de l'exécution du pipeline",
        "📈 Le graphique de prix utilise clobTokenIds[0] comme tokenId — utilisait le mauvais champ",
        "🔒 Réponse API CircuitBreaker normalisée — gère les formes objet et chaîne",
        "💥 Crash toFixed lors de l'exécution du pipeline — coercition Number() ajoutée à tous les champs numériques",
      ],
      de: [
        "🛠️ PipelineLog neu geschrieben — keine veralteten Closures mehr, zuverlässiger Event-Queue-Drainer",
        "📡 SSE-Event-Parsing behoben — Agentenkarten aktualisieren sich jetzt korrekt bei Pipeline-Lauf",
        "📈 Preisdiagramm verwendet clobTokenIds[0] als tokenId — verwendete falsches Feld",
        "🔒 CircuitBreaker-API-Antwort normalisiert — verarbeitet Objekt- und String-Formen",
        "💥 toFixed-Absturz bei Pipeline-Lauf — Number()-Koerzion zu allen numerischen Feldern hinzugefügt",
      ],
    },
  },
  {
    version: "v0.2.0",
    released_at: "2026-01-10",
    highlight: {
      en: "Signals, orchestrator, trending markets, and CI/CD pipeline.",
      es: "Señales, orquestador, mercados en tendencia y pipeline CI/CD.",
      fr: "Signaux, orchestrateur, marchés tendance et pipeline CI/CD.",
      de: "Signale, Orchestrator, Trend-Märkte und CI/CD-Pipeline.",
    },
    features: {
      en: [
        "📡 Recent Signals panel wired to /api/signals with live updates",
        "🎛️ Orchestrator panel — candidate market queue, scan status, autopilot toggle",
        "🔥 Trending markets pill + Polymarket live feed integration",
        "🚀 GitHub Actions CI/CD with automatic Vercel deploy on push to main",
        "🌟 Market analysis page with glassmorphism card redesign",
        "♾️ Infinite scroll on markets browser with pagination sentinel",
      ],
      es: [
        "📡 Panel de Señales Recientes conectado a /api/signals con actualizaciones en vivo",
        "🎛️ Panel de orquestador — cola de mercados candidatos, estado del escaneo, interruptor de autopiloto",
        "🔥 Píldora de mercados en tendencia + integración del feed en vivo de Polymarket",
        "🚀 GitHub Actions CI/CD con despliegue automático en Vercel al hacer push a main",
        "🌟 Página de análisis de mercado con rediseño de tarjeta glassmorfismo",
        "♾️ Desplazamiento infinito en el navegador de mercados con centinela de paginación",
      ],
      fr: [
        "📡 Panneau Signaux Récents connecté à /api/signals avec mises à jour en direct",
        "🎛️ Panneau orchestrateur — file de marchés candidats, statut du scan, bascule autopilote",
        "🔥 Pilule des marchés tendance + intégration du flux en direct Polymarket",
        "🚀 GitHub Actions CI/CD avec déploiement Vercel automatique au push sur main",
        "🌟 Page d'analyse de marché avec redesign de carte glassmorphism",
        "♾️ Défilement infini sur le navigateur de marchés avec sentinelle de pagination",
      ],
      de: [
        "📡 Aktuelle-Signale-Panel mit /api/signals mit Live-Updates verdrahtet",
        "🎛️ Orchestrator-Panel — Kandidatenmarkt-Queue, Scan-Status, Autopilot-Umschalter",
        "🔥 Trend-Märkte-Pill + Polymarket-Live-Feed-Integration",
        "🚀 GitHub Actions CI/CD mit automatischem Vercel-Deploy bei Push auf main",
        "🌟 Marktanalyse-Seite mit Glasmorphismus-Karten-Redesign",
        "♾️ Endloses Scrollen im Märkte-Browser mit Paginierungs-Sentinel",
      ],
    },
    fixes: {
      en: [
        "🐛 toFixed crash prevented — Number() coercion on spread/sentiment/ev fields",
        "⟳ Infinite scroll sentinel wasn't triggering on short viewports — fixed",
        "🧪 All Cypress E2E specs now pass including crash guard scenarios",
        "📊 Circuit breaker badge border-radius and scanner column layout fixes",
      ],
      es: [
        "🐛 Fallo de toFixed prevenido — coerción Number() en campos de spread/sentimiento/ev",
        "⟳ El centinela de desplazamiento infinito no se activaba en viewports cortos — corregido",
        "🧪 Todas las especificaciones E2E de Cypress ahora pasan incluyendo escenarios de guardia contra fallos",
        "📊 Correcciones de radio de borde del badge del interruptor de circuito y diseño de columna del escáner",
      ],
      fr: [
        "🐛 Crash toFixed évité — coercition Number() sur les champs spread/sentiment/ev",
        "⟳ Le sentinel de défilement infini ne se déclenchait pas sur les viewports courts — corrigé",
        "🧪 Toutes les specs E2E Cypress passent maintenant, y compris les scénarios de protection contre les crashs",
        "📊 Corrections du border-radius du badge du disjoncteur et du layout des colonnes du scanner",
      ],
      de: [
        "🐛 toFixed-Absturz verhindert — Number()-Koerzion auf spread/sentiment/ev Feldern",
        "⟳ Endlos-Scroll-Sentinel wurde auf kurzen Viewports nicht ausgelöst — behoben",
        "🧪 Alle Cypress E2E-Specs bestehen jetzt einschließlich Absturz-Schutz-Szenarien",
        "📊 Circuit-Breaker-Badge border-radius und Scanner-Spalten-Layout Korrekturen",
      ],
    },
  },
  {
    version: "v0.1.0",
    released_at: "2025-12-20",
    highlight: {
      en: "Initial release — Quantik Ultimate AI Trading terminal.",
      es: "Lanzamiento inicial — Terminal de Trading IA definitivo de Quantik.",
      fr: "Version initiale — Terminal de Trading IA ultime de Quantik.",
      de: "Erstveröffentlichung — Quantik Ultimate KI-Trading-Terminal.",
    },
    features: {
      en: [
        "🏠 Dashboard with live wallet balance, positions, and P&L",
        "📊 Markets browser with search, filters, and liquidity grades",
        "💼 Portfolio view with open positions and trade history",
        "🔮 Market pipeline — 7-agent AI analysis (Aura, Flux, Oracle, Edge, Clause, Lucifer, Sigma)",
        "🎨 Glassmorphism dark UI with iOS-inspired design tokens and color system",
        "📱 Responsive layout with sidebar nav and mobile bottom tab bar",
        "⚠️ Emergency panic button — close all positions with one click",
        "📄 Paper mode — simulate trades without real execution",
      ],
      es: [
        "🏠 Dashboard con saldo de billetera en vivo, posiciones y P&L",
        "📊 Navegador de mercados con búsqueda, filtros y calificaciones de liquidez",
        "💼 Vista de cartera con posiciones abiertas e historial de trades",
        "🔮 Pipeline de mercado — análisis de IA de 7 agentes (Aura, Flux, Oracle, Edge, Clause, Lucifer, Sigma)",
        "🎨 UI oscura glassmorfismo con tokens de diseño y sistema de colores inspirados en iOS",
        "📱 Diseño responsivo con navegación en barra lateral y barra de pestañas inferior para móvil",
        "⚠️ Botón de pánico de emergencia — cerrar todas las posiciones con un clic",
        "📄 Modo paper — simular trades sin ejecución real",
      ],
      fr: [
        "🏠 Tableau de bord avec solde de portefeuille en direct, positions et P&L",
        "📊 Navigateur de marchés avec recherche, filtres et notes de liquidité",
        "💼 Vue portfolio avec positions ouvertes et historique des trades",
        "🔮 Pipeline de marché — analyse IA à 7 agents (Aura, Flux, Oracle, Edge, Clause, Lucifer, Sigma)",
        "🎨 UI sombre glassmorphism avec tokens de design et système de couleurs inspirés d'iOS",
        "📱 Mise en page responsive avec navigation en barre latérale et barre d'onglets inférieure mobile",
        "⚠️ Bouton panique d'urgence — fermer toutes les positions en un clic",
        "📄 Mode paper — simuler les trades sans exécution réelle",
      ],
      de: [
        "🏠 Dashboard mit Live-Wallet-Guthaben, Positionen und P&L",
        "📊 Märkte-Browser mit Suche, Filtern und Liquiditätsbewertungen",
        "💼 Portfolio-Ansicht mit offenen Positionen und Trade-Historie",
        "🔮 Markt-Pipeline — 7-Agenten-KI-Analyse (Aura, Flux, Oracle, Edge, Clause, Lucifer, Sigma)",
        "🎨 Glasmorphismus dunkle UI mit iOS-inspirierten Design-Tokens und Farbsystem",
        "📱 Responsives Layout mit Seitenleisten-Navigation und mobilem Bottom-Tab-Bar",
        "⚠️ Notfall-Panik-Button — alle Positionen mit einem Klick schließen",
        "📄 Paper-Modus — Trades ohne echte Ausführung simulieren",
      ],
    },
    fixes: {
      en: [],
      es: [],
      fr: [],
      de: [],
    },
  },
];
